name: biometric_signature
description: Flutter biometric functionality for cryptographic signing and encryption
version: 4.1.1
homepage: https://github.com/chamodanethra/biometric_signature

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.2.6'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chamoda.nethra.biometric_signature
        pluginClass: BiometricSignaturePlugin
      ios:
        pluginClass: BiometricSignaturePlugin
